# Generated by Django 5.2.8 on 2025-11-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_Company', models.CharField(max_length=20)),
                ('Car_Model', models.CharField(max_length=20)),
                ('Car_Colour', models.CharField(max_length=20)),
                ('Fuel_Type', models.CharField(max_length=20)),
                ('Car_Price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
